name = "quicklocalize"
compatibility_date = "2024-04-19"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"
account_id = "06332387178d06e0a396a3e695643789"

[[ai_models]]
binding = "AI"
